# Site settings
title: Alex J Cornish
baseurl: "" 
url: "http://alexjcornish.com"
github_username:  suchgreatheights

# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap
  
# Google services
google_analytics: UA—57512699-4
